# Generated by Django 3.0.7 on 2020-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dishes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
