# Generated by Django 3.0.7 on 2020-06-25 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20200625_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='proteins',
        ),
        migrations.AddField(
            model_name='dishes',
            name='pfc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
