# Generated by Django 3.0.7 on 2020-07-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_auto_20200630_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('deception', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
