# Generated by Django 3.0.7 on 2020-08-03 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0009_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='like',
            field=models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков'),
        ),
        migrations.CreateModel(
            name='Thumbslike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnumber', models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков')),
                ('articles_current_liked', models.ManyToManyField(related_name='likes_object', to='dishes.Articles')),
                ('likedone', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thumbslike',
                'verbose_name_plural': 'Thumbslikes',
            },
        ),
    ]
