# Generated by Django 3.0.7 on 2020-08-03 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0010_auto_20200803_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likedone',
            field=models.ManyToManyField(related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
