# Generated by Django 3.0.7 on 2020-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0014_auto_20200804_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='like',
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], verbose_name='Голос'),
        ),
    ]
